# Generated by Django 5.0.6 on 2025-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_page',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timetable_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
